Plasforest:
	java -jar ~/Software/womtool-86.jar validate --inputs Plasforest.json Plasforest.wdl
	miniwdl check Plasforest.wdl

run_Plasforest:
	miniwdl run --debug --dir test-Plasforest --cfg ../../../miniwdl_production.cfg --input Plasforest.json Plasforest.wdl

Plasflow:
	java -jar ~/Software/womtool-86.jar validate --inputs Plasflow.json Plasflow.wdl
	miniwdl check Plasflow.wdl

run_Plasflow:
	miniwdl run --debug --dir test-Plasflow --cfg ../../../miniwdl_production.cfg --input Plasflow.json Plasflow.wdl

Pilon:
	java -jar ~/Software/womtool-86.jar validate --inputs Pilon.json Pilon.wdl
	miniwdl check Pilon.wdl

run_Pilon:
	miniwdl run --debug --dir test-Pilon --cfg ../../../miniwdl_production.cfg --input Pilon.json Pilon.wdl


