#
# PlasForest
#
Plasforest:
	java -jar ~/Software/womtool-86.jar validate --inputs Plasforest.json Plasforest.wdl
	miniwdl check Plasforest.wdl

run_Plasforest:
	miniwdl run --debug --dir test-Plasforest --cfg ../../../miniwdl_production.cfg --input Plasforest.json Plasforest.wdl


#
# Plasflow
#
Plasflow:
	java -jar ~/Software/womtool-86.jar validate --inputs Plasflow.json Plasflow.wdl
	miniwdl check Plasflow.wdl

run_Plasflow:
	miniwdl run --debug --dir test-Plasflow --cfg ../../../miniwdl_production.cfg --input Plasflow.json Plasflow.wdl

#
# Pilon
#
Pilon:
	java -jar ~/Software/womtool-86.jar validate --inputs Pilon.json Pilon.wdl
	miniwdl check Pilon.wdl

run_Pilon:
	miniwdl run --debug --dir test-Pilon --cfg ../../../miniwdl_production.cfg --input Pilon.json Pilon.wdl


#
# Polca
#
Polca:
	java -jar ~/Software/womtool-86.jar validate --inputs Polca.json Polca.wdl
	miniwdl check Polca.wdl

run_Polca:
	miniwdl run --debug --dir test-Polca --cfg ../../../miniwdl_production.cfg --input Polca.json Polca.wdl

#
# CirclatorAll
#
CirclatorAll:
	java -jar ~/Software/womtool-86.jar validate --inputs CirclatorAll.json CirclatorAll.wdl
	miniwdl check CirclatorAll.wdl

run_CirclatorAll:
	miniwdl run --debug --dir test-CirclatorAll --cfg ../../../miniwdl_production.cfg --input CirclatorAll.json CirclatorAll.wdl


